# Generated by Django 3.2.7 on 2021-10-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionmodel',
            name='author',
            field=models.CharField(default='Willy', max_length=240),
        ),
    ]
