# Generated by Django 3.2.7 on 2021-10-10 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='published_0n',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestionmodel',
            name='published_0n',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
