# Generated by Django 3.2.7 on 2021-10-10 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211010_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='published_0n',
            new_name='published_on',
        ),
        migrations.RenameField(
            model_name='suggestionmodel',
            old_name='published_0n',
            new_name='published_on',
        ),
    ]
