# Generated by Django 3.2.7 on 2022-03-14 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0011_auto_20220313_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.CharField(max_length=240, null=True)),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(max_length=144, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('image_description', models.CharField(max_length=240, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='post',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.gallerymodel'),
        ),
    ]
