# Generated by Django 3.2.7 on 2022-04-20 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0012_auto_20220314_0053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.gallerymodel'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='gallery',
            field=models.CharField(max_length=240),
        ),
    ]
