# Generated by Django 3.2.7 on 2022-05-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20220420_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
