# Generated by Django 3.2.7 on 2022-05-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
