# Generated by Django 3.2.7 on 2022-05-18 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_gallerymodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymodel',
            name='image',
        ),
    ]
